import { CarListing } from './types';

export const carListings: CarListing[] = [
  {
    id: 'pagani-utopia-2026',
    title: "2026 Pagani Utopia RWD",
    location: "Monaco, Monaco",
    year: "2026",
    specs: ["100 Km", "12 Cylinder", "864 HP"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2734-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2974-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2975-1.jpg"
    ],
    description: "The 2026 Pagani Utopia represents the pinnacle of automotive engineering and design, combining raw power with unparalleled luxury. This masterpiece features a potent 12-cylinder engine producing 864 horsepower, delivering an extraordinary driving experience.",
    specifications: [
      { label: "Year", value: "2026" },
      { label: "Location", value: "Monaco, Monaco" },
      { label: "Address", value: "17 Av. Albert II, 98000 Monaco" },
      { label: "Mileage", value: "100 km (62 mi)" },
      { label: "Engine", value: "12 Cylinder" },
      { label: "Gearbox", value: "Automatic" },
      { label: "Car type", value: "Roadster" },
      { label: "Drive Train", value: "RWD" },
      { label: "Fuel Type", value: "Other" },
      { label: "Power", value: "864 hp (644 kw)" },
      { label: "Condition", value: "New" },
      { label: "VIN", value: "ZA94U11EC8XXXXXXXX" },
      { label: "Exterior Color", value: "Custom" },
      { label: "Interior Color", value: "Custom" }
    ],
    features: [
      "12 Cylinder Engine",
      "Automatic Transmission",
      "Rear Wheel Drive",
      "Custom Exterior",
      "Custom Interior",
      "Limited Production",
      "Hypercar Performance",
      "Advanced Aerodynamics",
      "Carbon Fiber Construction",
      "Premium Sound System",
      "Navigation System",
      "Climate Control"
    ],
    visible: true
  },
  {
    id: 'mclaren-artura-2025',
    title: "2025 McLaren Artura TechLux",
    location: "Las Vegas, NV, United States",
    year: "2025",
    specs: ["102 Miles", "6 Cylinder", "TechLux Spec"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2505.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2506.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2507.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2508.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2509.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2510.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2511.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2512.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2513.jpg"
    ],
    description: "McLaren Las Vegas is proud to present this 2025 McLaren Artura TechLux Spider in Belize Blue and Mojave Tan with Black and Teal Accent.\n\nOther manufacturer options include:\n- Exterior Elite Paint - Belize Blue\n- Sports Exhaust\n- TechLux Spec\n- America's Accessories Pack\n- Technology Pack\n- 10-Spoke SLW Star Forged Alloy Wheels",
    specifications: [
      { label: "Year", value: "2025" },
      { label: "Mileage", value: "102 mi (164 km)" },
      { label: "Location", value: "3131 LAS VEGAS BLVD S SPACE 115-A" },
      { label: "Engine", value: "6 Cylinder" },
      { label: "Body Style", value: "Cabriolet" },
      { label: "Drive Train", value: "RWD" },
      { label: "Fuel Type", value: "Petrol" },
      { label: "Condition", value: "New" },
      { label: "VIN", value: "SBM16BEA4SW002776" },
      { label: "Exterior Color", value: "Blue" },
      { label: "Interior Color", value: "Two Tone" },
      { label: "Reference", value: "25ML0031" }
    ],
    features: [
      "TechLux Specification",
      "Sports Exhaust",
      "10-Spoke SLW Star Forged Wheels",
      "America's Accessories Pack",
      "Technology Pack",
      "Elite Paint - Belize Blue",
      "Mojave Tan Interior",
      "Black and Teal Accents",
      "Racing Simulator Available",
      "World-Class Service"
    ],
    visible: true
  },
  {
    id: 'lamborghini-aventador-2012',
    title: "2012 Lamborghini Aventador LP 700-4 Coupe 2D",
    location: "Costa Mesa, CA, United States",
    year: "2012",
    specs: ["14,667 Miles", "V12 Engine", "691 HP"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2538.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2539.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2540.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2541.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2542.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2543.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2544.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2545.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2546.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2547.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2548.jpg"
    ],
    description: "The 2012 Lamborghini Aventador LP700-4 is an iconic supercar that epitomizes Italian engineering and design. This example features a clean Carfax & Autocheck, and is finished in stunning Nero Nemesis with a full car stealth Xpel PPF. At its heart lies a 6.5-liter V12 engine producing 691 horsepower and 509 lb-ft of torque, enabling it to accelerate from 0 to 60 mph in just 2.9 seconds and reach a top speed of 217 mph. The Aventador features a lightweight carbon-fiber monocoque chassis, enhancing both performance and handling. Its aggressive styling is complemented by signature scissor doors and a driver-focused cockpit adorned with premium materials and advanced technology. Combining breathtaking speed with luxurious comfort, the 2012 Aventador LP700-4 remains a standout in the realm of high-performance exotics.\n\nAftermarket Modifications:\nCarbon Fiber exterior accents\nIPE exhaust system\n20' Front & 21' Rear carbon fiber trimmed PUR wheels",
    specifications: [
      { label: "Year", value: "2012" },
      { label: "Mileage", value: "14,667 mi (23,604 km)" },
      { label: "Location", value: "2960 Airway Ave STE B102, Costa Mesa, CA" },
      { label: "Engine", value: "6.5L V12" },
      { label: "Power", value: "691 hp" },
      { label: "Transmission", value: "7-Speed Automatic" },
      { label: "Drive Train", value: "All-Wheel Drive" },
      { label: "Fuel Type", value: "Petrol" },
      { label: "Condition", value: "Used" },
      { label: "VIN", value: "ZHWUC1ZD1CLA00557" },
      { label: "Exterior Color", value: "Black" },
      { label: "Interior Color", value: "Black" },
      { label: "Reference", value: "LA-0557" }
    ],
    features: [
      "Carbon Fiber Monocoque",
      "Scissor Doors",
      "IPE Exhaust System",
      "Carbon Fiber Exterior Accents",
      "PUR Wheels (20\"/21\")",
      "Xpel Paint Protection Film",
      "All-Wheel Drive",
      "Launch Control",
      "Carbon Ceramic Brakes",
      "Premium Sound System",
      "Navigation System"
    ],
    visible: true
  },
  {
    id: 'ferrari-f40-1990',
    title: "1990 Ferrari F40",
    location: "West Hollywood, CA, United States",
    year: "1990",
    specs: ["18,900 Miles", "8 Cylinder", "Manual"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2528.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2529.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2530.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2531.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2532.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2533.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2534.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2535.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2536.jpg"
    ],
    description: "1990 Ferrari F40\n1 of 213 United States Cars\nOriginal Tool Kit\nOriginal Owner's Manuals\nOriginal Window Sticker\nService Records Available Upon Request\n\nThe Ferrari F40 is known as Enzo's last masterpiece. The last mark that he could leave on his historic legacy. The F40 is known to all collectors and enthusiasts as one of the best cars ever made. It was the first road car to break the 200 MPH Barrier.\n\nSpecialty car collection is proud to offer this 1990 Ferrari F40. It is one of only 213 cars produced for The Unites States market. Originaly sold at Hollywood sports cars in1990, The first and only owner always maintained the car and made sure it stayed complete. The original three piece Schedoni luggage,  original tool kit and owner's manuals are all included with the car. Also with the car is an extencive service history and documentation back to when it was new.",
    specifications: [
      { label: "Year", value: "1990" },
      { label: "Mileage", value: "18,900 mi (30,417 km)" },
      { label: "Location", value: "8929 W Sunset Blvd, West Hollywood, CA 90069" },
      { label: "Engine", value: "8 Cylinder" },
      { label: "Gearbox", value: "Manual" },
      { label: "Drive Train", value: "RWD" },
      { label: "Fuel Type", value: "Petrol" },
      { label: "Power", value: "471 hp (351 kw)" },
      { label: "Condition", value: "Used" },
      { label: "VIN", value: "ZFFMN34A4L0086118" },
      { label: "Exterior Color", value: "Red" },
      { label: "Interior Color", value: "Red" }
    ],
    features: [
      "Original Schedoni Luggage",
      "Original Tool Kit",
      "Original Owner's Manuals",
      "Original Window Sticker",
      "Complete Service History",
      "1 of 213 US-Spec Cars",
      "Single Owner from New",
      "Twin-Turbocharged V8",
      "5-Speed Manual Transmission",
      "Carbon Fiber Construction",
      "Iconic Design"
    ],
    visible: true
  },
  {
    id: 'bugatti-chiron-2019',
    title: "2019 Bugatti Chiron",
    location: "Beverly Hills, CA, United States",
    year: "2019",
    specs: ["3,425 Miles", "Coupe", "Two Tone Interior"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2514.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2515.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2516.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2517.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2518.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2519.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2520.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2521.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2522.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2523.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2524.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2525.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2526.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2527.jpg"
    ],
    description: "A stunning example of automotive excellence, this 2019 Bugatti Chiron represents the pinnacle of hypercar engineering and luxury.",
    specifications: [
      { label: "Year", value: "2019" },
      { label: "Mileage", value: "3,425 mi (5,512 km)" },
      { label: "Location", value: "8833 W Olympic Blvd, Beverly Hills, CA" },
      { label: "Body Style", value: "Coupe" },
      { label: "Condition", value: "Used" },
      { label: "VIN", value: "VF9SP3V34KM795201" },
      { label: "Exterior Color", value: "Black" },
      { label: "Interior Color", value: "Two Tone" },
      { label: "Reference", value: "CS700R" }
    ],
    features: [
      "W16 Engine",
      "Quad Turbochargers",
      "7-Speed Dual-Clutch Transmission",
      "All-Wheel Drive",
      "Carbon Fiber Construction",
      "Active Aerodynamics",
      "Luxury Interior",
      "Climate Control",
      "Navigation System",
      "Premium Sound System"
    ],
    visible: true
  }
];