import { JetListing } from './types';

export const jetListings: JetListing[] = [
  {
    id: 'gulfstream-gv-1998',
    title: "GULFSTREAM GV",
    location: "Ponte Vedra Beach, Florida, United States",
    year: "1998",
    specs: ["9,832 TTAF", "3 Crew", "51,000 ft Max Alt"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2849-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2850-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2851-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2852-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2853-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2854-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2855-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2856-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2857-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2858-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2859-1.jpg"
    ],
    description: "The Gulfstream V revolutionized long range corporate travel and remains the most popular, dependable aircraft in its class. It is capable of reaching destinations up to 6,000 nm away, at speeds up to Mach .88, in a spacious luxurious cabin.\n\nTurnkey G-V coming soon. Recent Engine Overhauls & Landing Gear Overhauled, 2020 Compliant (ADS-B Out, FANS-1A, CPDLC), RRCC, HAPP, MPP, & CASP, Recent Cosmetics in Immaculate Condition; Domestic/International WIFI, HUD, US Owned & Operated.",
    specifications: [
      { label: "Year", value: "1998" },
      { label: "Brand", value: "Gulfstream" },
      { label: "Location", value: "818 A1A N, Ponte Vedra Beach, FL 32082" },
      { label: "TTAF", value: "9,832" },
      { label: "Crew", value: "3" },
      { label: "Cruising Speed", value: "561 mph (903 kph)" },
      { label: "Max Range", value: "7,681 mi (12,361 km)" },
      { label: "Max Takeoff Weight", value: "90,500 lbs (41,050 kg)" },
      { label: "Max Altitude", value: "51,000 ft (15,545 m)" },
      { label: "Cabin Length", value: "50 ft (15 m)" },
      { label: "Cabin Height", value: "6 ft (2 m)" },
      { label: "Cabin Width", value: "7 ft (2 m)" },
      { label: "Exterior Height", value: "26 ft (8 m)" },
      { label: "Exterior Length", value: "96 ft (29 m)" },
      { label: "Wing Span", value: "94 ft (29 m)" },
      { label: "Serial Number", value: "552" },
      { label: "Registration", value: "N90JE" }
    ],
    features: [
      "Recent Engine Overhauls",
      "Landing Gear Overhauled",
      "2020 Compliant",
      "ADS-B Out",
      "FANS-1A",
      "CPDLC",
      "RRCC",
      "HAPP",
      "MPP",
      "CASP",
      "Recent Cosmetics",
      "Domestic/International WIFI",
      "HUD",
      "US Owned & Operated",
      "Spacious Luxurious Cabin",
      "Long Range Capability"
    ],
    visible: true
  },
  {
    id: 'bombardier-challenger-604',
    title: "2004 Bombardier Challenger 604",
    location: "Monaco, Monaco",
    year: "2004",
    specs: ["9 Passengers", "Low Time", "EASA Compliant"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1551.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1549.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1552.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1553.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1556.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1557.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1558.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1559.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1560.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1562.jpg"
    ],
    description: "The Challenger 604 has established a proven track record for dependability, reliability and outstanding value, making it one of the best-selling jet in its class. Offering the widest cabin of any comparable model in its league, matched with ample stand up room and a passive noise insulation, it provides superior cabin comfort and is well suited for any mission thanks to an intercontinental range and fast cruising speed.\n\nHighlights:\n•Low Time\n•Fully Enrolled on Programs\n•9 PAX Configuration\n•No Known Damage History\n•EASA Compliant",
    specifications: [
      { label: "Year", value: "2004" },
      { label: "Location", value: "41 Rue Grimaldi, 98000 Monaco" },
      { label: "Engine 1", value: "GE CF34-3B (s/n: 950093)" },
      { label: "Engine 1 Time", value: "5,916 TSN / 2,530 CSN" },
      { label: "Engine 2", value: "GE CF34-3B (s/n: 950094)" },
      { label: "Engine 2 Time", value: "5,916 TSN / 2,530 CSN" },
      { label: "Maintenance", value: "48M completed 2021" },
      { label: "Configuration", value: "9 Passenger Executive" }
    ],
    features: [
      "Rockwell Collins ProLine 4 Legacy Avionics",
      "Collins Airshow 400 Moving Map",
      "Two Cabin Monitors",
      "AirCell Iridium Satellite Phone",
      "Beige Leather Seats (2016 Refurbishment)",
      "Convertible to Four Beds",
      "Two Cabin Zones",
      "Equipped Galley with Microwave",
      "Coffee Maker and Chiller",
      "Four Place Double Club Seats",
      "Three Place Divan",
      "Aft Lavatory",
      "White Base Paint with Blue/Grey Accents (2016)",
      "GE OnPoint Engine Program",
      "No Known Damage History"
    ],
    visible: true
  },
  {
    id: 'cessna-citation-xlsplus',
    title: "2013 Textron Cessna Citation XLS+",
    location: "Donaueschingen, Germany",
    year: "2013",
    specs: ["8 Passengers", "2,755 TTAF", "ADSB Out"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1652.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1653.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1654.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1658.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1660.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1663.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1661.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1662.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1656.jpg"
    ],
    description: "Engines:\n2 x Pratt & Whitney PW 545C, FADEC Controlled and enrolled on Power Advantage+ Engine Program, TBO 5.000 hrs, 2 x 4.119 lb thrust\n\nAPU:\nHoneywell RE 100(XL) on AUX Advantage APU Program\n\nHighlights:\nSecond FMS 3000, CVR/FDR, TCAS II, EGPWS Mark V, PowerAdvantage+ Engine Program, SATCOM and Airshow, FADEC, E-Charts",
    specifications: [
      { label: "Year", value: "2013" },
      { label: "Location", value: "78 Donaueschingen, Germany" },
      { label: "TTAF", value: "2,755" },
      { label: "Serial Number", value: "560XL-6140" },
      { label: "Registration", value: "D-CMHS" },
      { label: "Range", value: "1,858 nm (3,440 km)" },
      { label: "Max Speed", value: "441 KTAS (815 km/h)" },
      { label: "Max Takeoff Weight", value: "20,200 lb (9,163 kg)" }
    ],
    features: [
      "Collins Proline 21 Avionics",
      "Dual Collins VHF-4000",
      "Dual Collins FMS 3000 with WAAS/LPV",
      "TCAS II Collins 4000 Change 7.1",
      "8+1 Cabin Configuration",
      "4 Club Seats",
      "Double Seat Couch",
      "Belted Toilet Seat",
      "Cabin and Cockpit AC Power",
      "Lavatory with Sink",
      "SATCOM and WIFI",
      "Airshow Entertainment",
      "Hot Coffee Pot",
      "RosenView Cabin Briefer",
      "No Damage History",
      "Power Advantage+ Program",
      "AUX Advantage APU Program"
    ],
    visible: true
  },
  {
    id: 'global-xrs-2010',
    title: "2010 Global XRS - Top Condition",
    location: "Germany",
    year: "2010",
    specs: ["13 Passengers", "3,500 TTAF", "Recent 120M"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1213.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1214.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1215.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1527.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1528.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1529.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1532.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1538.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1541.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1542.jpg"
    ],
    description: "LATE MODEL GLOBAL XRS WITH RECENT 120M, PAINT AND INTERIOR\n\nThe aircraft has a very attractive avant-garde design with a black exterior and an interior composed of black wood and white leather paired with light grey cloth divans and a charcoal carpet, forward galley, 13 passenger interior. Forward cabin with a double club and foldout tables with leather inlays. Mid cabin with four seat conference group opposite a bespoke credenza with leather inlays. Aft cabin with dual three place divans that easily convert into two large beds or one kingsize double. Large baggage hold. Recent 120M with new paint and interior, very low utilisation since. Pristine turn-key condition!\n\nFully programmed with Rolls Royce Corporate Care, Honeywell MSP and SmartPartsPlus\n\nEurope based since birth with top pedigree!\n\nThis is a rare opportunity to acquire a pristine attractive design Global XRS! Turn-key and ready to go!\n\nEXCLUSIVE CO-LISTING WITH COLIBRI AIRCRAFT",
    specifications: [
      { label: "Year", value: "2010" },
      { label: "Location", value: "Germany" },
      { label: "Type", value: "Large Cabin" },
      { label: "TTAF", value: "3,500" },
      { label: "Serial Number", value: "9333" },
      { label: "Registration", value: "D-ACCF" },
      { label: "Crew", value: "3" },
      { label: "Flight Attendant", value: "1" }
    ],
    features: [
      "Recent 120M Inspection",
      "New Paint and Interior",
      "Black Wood & White Leather Interior",
      "Forward Galley",
      "13 Passenger Configuration",
      "Double Club Seating",
      "Four Seat Conference Group",
      "Bespoke Credenza",
      "Convertible Divans",
      "Large Baggage Hold",
      "Rolls Royce Corporate Care",
      "Honeywell MSP",
      "SmartPartsPlus Program",
      "European Pedigree",
      "Turn-key Condition"
    ],
    visible: true
  },
  {
    id: 'gulfstream-g550-2013',
    title: "Gulfstream G550 for lease",
    location: "Ponte Vedra Beach, Florida, United States",
    year: "2013",
    specs: ["18 Passengers", "3,923 TTAF", "Large Cabin"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2549.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2550.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2551.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2552.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2553.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2554.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2555.jpg"
    ],
    description: "Available Immediately for Lease! Embodying exceptional international performance, the Gulfstream G550 exhibits efficiency like no other, with the capacity to fly 6,750 nautical miles or 12,501 kilometers nonstop. Remarkably, it is also capable of operating out of high-altitude airports and those with short runways. The G550 can seamlessly transport up to 18 passengers, still maintaining the range to fly nonstop for over 12 hours.\n\nPowered by a pair of Rolls-Royce engines, the G550 leads the pack in its class with the most thrust, facilitating journeys from Shanghai to Los Angeles or New York to Dubai nonstop at Mach 0.80. Even at Mach 0.85, it offers nonstop travel from London to Tokyo or Los Angeles. The Gulfstream G550 masterfully combines performance, efficiency, and luxury, truly setting the standard for business travel.",
    specifications: [
      { label: "Year", value: "2013" },
      { label: "Location", value: "818 A1A N, Ponte Vedra Beach, FL 32082" },
      { label: "Type", value: "Large Cabin" },
      { label: "TTAF", value: "3,923" },
      { label: "Cruising Speed", value: "476 kn (882 kph)" },
      { label: "Max Range", value: "8,000 mi (12,875 km)" },
      { label: "Max Takeoff Weight", value: "91,000 lbs (41,277 kg)" },
      { label: "Max Altitude", value: "51,000 ft (15,545 m)" },
      { label: "Cabin Length", value: "43 ft (13 m)" },
      { label: "Cabin Height", value: "6 ft (2 m)" },
      { label: "Cabin Width", value: "7 ft (2 m)" },
      { label: "Serial Number", value: "5430" },
      { label: "Registration", value: "N5430G" }
    ],
    features: [
      "Available for Immediate Lease",
      "18 Passenger Capacity",
      "Intercontinental Range",
      "High-Altitude Airport Capability",
      "Short Runway Operations",
      "12+ Hour Nonstop Range",
      "Rolls-Royce Engines",
      "Mach 0.80-0.85 Cruise Speed",
      "Spacious Cabin Interior",
      "Advanced Avionics",
      "Premium Comfort Features"
    ],
    visible: true
  }
];