import { RealEstateListing } from './types';

export const realEstateListings: RealEstateListing[] = [
  {
    id: 'villa-arenada',
    title: "Villa Arenada. Designer Villas In A Mediterranean Oasis",
    location: "Località Is Molas, Sardinia, Italy",
    specs: ["2 Bedrooms", "3 Bathrooms", "3,649 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2965-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2966-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2967-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2968-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2969-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2970-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2971-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2972-1.jpg"
    ],
    description: "Villa Arenada is a luxury residence designed by archistar Massimiliano Fuksas, located in the prestigious Is Molas Resort complex in southern Sardinia. This villa with private pool of 4045 square meters is an exclusive solution, enriched by fine furnishings with elegance and comfort in every detail. On the ground floor we find a large open space with kitchen, dining room and a living room overlooking a private garden, while the master bedroom with en suite bathroom provides privacy and tranquility. On the second floor, a second bedroom with en suite bathroom and a terrace with spa area and Jacuzzi.\n\nThe villa also has access to the 27-hole golf course, as well as allI resort amenities including Chef-at-Home for local culinary experiences. Located near historic sites such as the Archaeological Park of Nora, this villa offers the ultimate in luxury in one of Sardinia's most beautiful locations.Between pristine beaches, crystal clear coves, and a perfect setting for outdoor activities, at Is Molas you will discover a unique way to experience Sardinia.",
    specifications: [
      { label: "Living Area", value: "3,649 sqft" },
      { label: "Bedrooms", value: "2" },
      { label: "Bathrooms", value: "3" },
      { label: "Property Type", value: "Villa" }
    ],
    features: [
      "Terrace",
      "Garden",
      "Pool",
      "Jacuzzi",
      "Golf View",
      "Panoramic / Scenic View",
      "Privacy"
    ],
    visible: true
  },
  {
    id: 'triplex-sanctuary-ellington',
    title: "Triplex 5 Bedroom Luxury Villa In The Sanctuary By Ellington",
    location: "Mohammed Bin Rashid City - Nad Al Sheba - Dubai - United Arab Emirates, Dubai, Dubai, United Arab Emirates",
    specs: ["5 Bedrooms", "6 Bathrooms", "6,936 sqft", "9,985 sqft lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2963-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2956-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2957-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2958-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2960-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2961-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2962-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2964-1.jpg"
    ],
    description: "Picture spacious, light-filled interiors that blend minimalism with high-end finishes, large windows that offer expansive views of landscaped gardens or rolling hills, and outdoor spaces designed for relaxation and mindfulness. The sounds of nature, birdsong, rustling leaves, and a gentle breeze might replace city noise, making it a perfect place for quiet reflection or a comfortable social gathering with friends and family.\n\nThe Sanctuary by Ellington isn't just a place to live—it's a place to thrive. It's where luxury meets nature, where wellness is woven into every detail, and where a sense of belonging is nurtured within a peaceful, connected community. If you're seeking a life of tranquility, beauty, and balance, The Sanctuary is where you'll find it.\n\nWith wellness-focused amenities like a fitness center and walking trails, residents enjoy a balanced lifestyle. The community fosters connection with on-site social spaces and concierge services while maintaining privacy and security. Sustainable design, eco-friendly practices, and thoughtful conveniences ensure that every detail supports a high standard of living.\n\nThis villa offers a large open plan living and dining area, a show kitchen and a prep kitchen. It has en-suite bedrooms and further features a study room and lounge areas and a clubhouse.\n\nReady to experience a life of luxury and tranquility?",
    specifications: [
      { label: "Living Area", value: "6,936 sqft" },
      { label: "Lot Size", value: "9,985 sqft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "6" },
      { label: "Property Type", value: "Villa" }
    ],
    features: [
      "Lakefront",
      "Gated Community",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "Investment Property",
      "New Built",
      "Indoor Pool",
      "Elevator",
      "Library",
      "Steam Room",
      "Air Conditioning",
      "Fitness Center / Gym",
      "High Ceiling",
      "Washer Dryer",
      "Kitchen island",
      "Laundry Room",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Parking",
      "Garden",
      "Balcony",
      "Gate",
      "Playground"
    ],
    visible: true
  },
  {
    id: 'kaniaro-seafront-estate',
    title: "Kaniaro Seafront Estate In Northeast Corfu",
    location: "Corfu, Greece, Corfu, Decentralized Administration of Peloponnese, Western Greece and the Ionian, Greece",
    specs: ["9 Bedrooms", "9 Bathrooms", "5,878 sqft", "2.22 ac lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2925-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2923-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2924-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2926-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2927-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2928-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2929-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2930-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2931-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2932-1.jpg"
    ],
    description: "Kaniaro is an exceptional seafront estate that blends history with luxury, offering an unparalleled living experience in one of the most sought after locations on Corfu.\n\nNestled on the beautiful northeastern coast of Corfu, just a five minute drive from the vibrant heart of Kassiopi, Kaniaro is truly one of a kind seafront estates offering the rare combination of historical charm and modern luxury. Originally an 18th-century olive press, this special property has been thoughtfully restored to preserve its original features while incorporating all the comforts of contemporary living. Set directly on the sea with private access to a sandy beach and a 10 meter jetty, Kaniaro presents a truly private and tranquil retreat.\n\nThe estate is approached through large electric gates, leading down a long, winding drive that meanders through ancient olive groves. The main building, located right next to the crystal clear waters of the Ionian Sea, offers sweeping views of the coastline. The grounds, spanning nearly 9,000 square meters, are beautifully landscaped with an array of Mediterranean flora, including circa sixty olive trees, pomegranates, lemons, oranges, kumquats, figs, almonds, and avocados, creating a lush and peaceful oasis.\n\nTo the north of the property lies a tranquil monastery and a stunning, secluded sandy beach, while to the south, within a short walk, another long sandy beach with restaurants offering a perfect mix of seclusion and convenience. The 20 meter infinity swimming pool, positioned on an elevated terrace, is nestled within the lush gardens and offers breathtaking views of the sea. The swimming pool area features ample sunbathing space, a fully equipped bar, an outdoor WC and shower facilities. For ultimate relaxation, there is also a private massage area and a fully equipped outdoor gym, both overlooking the sea.\n\nIn front of the main building, a vast terrace extends over the water, providing extensive outdoor sitting and dining areas, complete with a bar, pizza oven, and pergolas draped in mature wisteria. Just a few steps from the water, a private sunbathing area and floating 10 meter jetty offer direct access to the turquoise, sandy waters, where several boats can moor and one can swim in arguably some of the very best water in Greece.\n\nThe main villa is spread across two levels. On the ground floor, a spacious living room with a grand fireplace opens to the library and indoor dining area and a fully equipped kitchen with a large walk in cold room and separate guest WC. This level also features an independent bedroom with an ensuite bathroom and direct access to the lovely terrace. The first floor is dedicated to the master suite, which boasts a dressing room, a large ensuite bathroom with both a bathtub and a shower, and the bedroom has panoramic sea views. Additionally, there are three more bedrooms, each with its own shower rooms, two of which are ensuite, offering comfort and privacy for family and guests.\n\nAt the rear of the main villa, an independent guest house is positioned on a higher level, ensuring complete privacy. The building includes two double bedrooms on a mezzanine level, each with a sitting room, ensuite shower room, and private terraces. There is an en-suite studio room at the rear and on the ground level, there is an additional guest bedroom with an ensuite bathroom, plus there is a large laundry room with a WC.\n\nFor those looking to expand, the estate offers the possibility to build on the land. Pre-Approved Planning Permission for a 5 Bedroom ensuite bathrooms property of 186 m2 123 m2 basement on the land with direct sea access. Planning can be changed and simplified to add more guest suits and staff quarters to the main property.\n\nWhether you're looking for a family home or an exclusive holiday retreat, this unique property provides the perfect combination of privacy, elegance, and proximity to Corfu's natural beauty and vibrant local culture.",
    specifications: [
      { label: "Living Area", value: "5,878 sqft" },
      { label: "Lot Size", value: "2.22 ac" },
      { label: "Bedrooms", value: "9" },
      { label: "Bathrooms", value: "9" },
      { label: "Property Type", value: "Estate" },
      { label: "Year Built", value: "18th century" },
      { label: "Renovation", value: "Fully Restored" }
    ],
    features: [
      "Beachfront",
      "Water View",
      "Sea View",
      "Waterfront",
      "Seafront",
      "Privacy",
      "Panoramic / Scenic View",
      "Mansion",
      "Renovated",
      "Stone Countertops",
      "Library",
      "Air Conditioning",
      "Office",
      "Fitness Center / Gym",
      "High Ceiling",
      "Washer Dryer",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Fireplace",
      "Gas Stovetop",
      "Terrace",
      "Pergola",
      "Outdoor Living Space",
      "Parking",
      "Garden",
      "Balcony",
      "Private Beach",
      "Fire Pit",
      "Gate",
      "Pool",
      "Outdoor Kitchen",
      "Playground"
    ],
    visible: true
  },
  {
    id: 'woodley-park-residence',
    title: "2833 27th St Nw",
    location: "Washington, District of Columbia, United States",
    specs: ["7 Bedrooms", "7 Bathrooms", "6,900 sqft", "0.23 ac lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1868.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1869.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1870.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1871.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1877.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1879.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1887.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1888.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1891.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1895.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1894.jpg"
    ],
    description: "Welcome to this extraordinary residence in Washington DC's prestigious Woodley Park neighborhood. This meticulously renovated home combines classic architecture with modern luxury, offering approximately 6,900 square feet of sophisticated living space.\n\nThe main level features a grand foyer, formal living and dining rooms, and a gourmet kitchen that opens to a family room with French doors leading to a private terrace. The chef's kitchen is equipped with premium appliances, custom cabinetry, and a large center island.\n\nThe upper levels house seven bedrooms including a luxurious primary suite with a sitting area, custom walk-in closets, and a spa-like bathroom. Additional bedrooms feature en-suite bathrooms and ample closet space.\n\nThe lower level includes a recreation room, wine cellar, and additional storage space. The property also features a two-car garage, professionally landscaped grounds, and multiple outdoor living spaces.\n\nKey Features:\n- Completely renovated\n- Gourmet kitchen\n- Wine cellar\n- Multiple fireplaces\n- Two-car garage\n- Private terrace\n- Smart home technology\n- Security system",
    specifications: [
      { label: "Living Area", value: "6,900 sqft" },
      { label: "Lot Size", value: "0.23 ac" },
      { label: "Bedrooms", value: "7" },
      { label: "Bathrooms", value: "7" },
      { label: "Property Type", value: "Single Family Home" },
      { label: "Year Built", value: "1925" },
      { label: "Renovation", value: "2023" }
    ],
    features: [
      "Privacy",
      "Renovated",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Wine Cellar",
      "Fireplace",
      "Terrace",
      "Garage",
      "Garden",
      "Balcony"
    ],
    visible: true
  },
  {
    id: 'nad-al-sheba-villa',
    title: "Luxury 5 Bedroom Villa in Nad Al Sheba",
    location: "Nad Al Sheba - Dubai - United Arab Emirates",
    specs: ["5 Bedrooms", "6 Bathrooms", "6,000 sqft", "8,000 sqft lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2080.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2081.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2084.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2085.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2088.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2090.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2095.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2098.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2102.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2104.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2105.jpg"
    ],
    description: "Experience luxury living in this contemporary villa located in the prestigious Nad Al Sheba community. This stunning property combines modern architecture with premium finishes and amenities, creating an ideal family home in Dubai.\n\nThe villa features a spacious open-plan layout with high ceilings and floor-to-ceiling windows that flood the interior with natural light. The ground floor includes a formal living room, family room, dining area, and a state-of-the-art kitchen equipped with premium appliances and custom cabinetry.\n\nThe five bedrooms are thoughtfully designed with en-suite bathrooms and built-in wardrobes. The master suite offers a private balcony, walk-in closet, and a luxurious bathroom with dual vanities and a freestanding tub.\n\nOutdoor amenities include a private swimming pool, landscaped garden, and covered parking for multiple vehicles. The property also features smart home technology, security systems, and maid's quarters.\n\nKey Features:\n- Contemporary design\n- Smart home technology\n- Private swimming pool\n- Covered parking\n- Maid's quarters\n- Security system\n- Premium finishes throughout",
    specifications: [
      { label: "Living Area", value: "6,000 sqft" },
      { label: "Lot Size", value: "8,000 sqft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "6" },
      { label: "Property Type", value: "Villa" },
      { label: "Year Built", value: "2023" }
    ],
    features: [
      "Privacy",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Garden",
      "Balcony",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'marbella-duplex-penthouse',
    title: "Stunning Duplex Penthouse With Breathtaking Views",
    location: "Marbella, Málaga, Spain",
    specs: ["4 Bedrooms", "4 Bathrooms", "3,875 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2007.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2008.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2010.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2011.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2013.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2014.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2016.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2019.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2023.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2026.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2025.jpg"
    ],
    description: "This exceptional duplex penthouse in Marbella offers luxurious living with panoramic views of the Mediterranean Sea and mountains. Located in a prestigious gated community, this property combines contemporary design with premium finishes and amenities.\n\nThe lower level features an open-plan living area with floor-to-ceiling windows, a modern kitchen with high-end appliances, and access to a spacious terrace perfect for outdoor dining and entertaining. The upper level houses the master suite with a private terrace, walk-in closet, and luxury bathroom, plus additional en-suite bedrooms.\n\nThe property includes multiple terraces offering stunning views, a private pool, and covered parking. Residents have access to community amenities including gardens, pools, and 24-hour security.\n\nKey Features:\n- Panoramic sea and mountain views\n- Private pool\n- Multiple terraces\n- High-end finishes\n- Smart home technology\n- 24-hour security\n- Covered parking\n- Community amenities",
    specifications: [
      { label: "Living Area", value: "3,875 sqft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "4" },
      { label: "Property Type", value: "Penthouse" },
      { label: "Year Built", value: "2023" }
    ],
    features: [
      "Ocean View",
      "Mountain View",
      "Sea View",
      "Gated Community",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Balcony",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'business-bay-57j6',
    title: "Business Bay 57J6 Dubai",
    location: "Business Bay - Dubai - United Arab Emirates",
    specs: ["4 Bedrooms", "5 Bathrooms", "4,500 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2052.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2054.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2056.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2057.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2059.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2062.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2063.jpg"
    ],
    description: "Experience luxury living in this stunning apartment located in Dubai's prestigious Business Bay district. This contemporary residence offers breathtaking views of the Dubai skyline and Burj Khalifa, combining modern design with premium finishes and amenities.\n\nThe apartment features an open-plan living space with floor-to-ceiling windows that flood the interior with natural light and showcase the spectacular city views. The modern kitchen is equipped with high-end appliances and custom cabinetry, perfect for both everyday living and entertaining.\n\nAll four bedrooms include en-suite bathrooms and built-in wardrobes, with the master suite offering a walk-in closet and a luxury bathroom. The property also features a maid's room with its own bathroom.\n\nResidents have access to world-class amenities including a swimming pool, fitness center, children's play area, and 24-hour security. The location offers easy access to Downtown Dubai, Dubai Mall, and major transportation links.\n\nKey Features:\n- Burj Khalifa and city views\n- Premium finishes\n- Smart home technology\n- Building amenities\n- 24-hour security\n- Parking space\n- Central location",
    specifications: [
      { label: "Living Area", value: "4,500 sqft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "5" },
      { label: "Property Type", value: "Apartment" },
      { label: "Year Built", value: "2023" }
    ],
    features: [
      "City View",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Elevator",
      "Air Conditioning",
      "Fitness Center / Gym",
      "Kitchen island",
      "Walk In Closet",
      "Open Kitchen",
      "Balcony",
      "Pool"
    ],
    visible: true
  }
];