import { RealEstateListing } from './types';

export const realEstateListings: RealEstateListing[] = [
  {
    id: 'kaniaro-seafront-estate',
    title: "Kaniaro Seafront Estate In Northeast Corfu",
    location: "Corfu, Greece, Corfu, Decentralized Administration of Peloponnese, Western Greece and the Ionian, Greece",
    specs: ["9 Bedrooms", "9 Bathrooms", "5,878 sqft", "2.22 ac lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2925-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2923-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2924-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2926-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2927-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2928-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2929-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2930-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2931-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2932-1.jpg"
    ],
    description: "Kaniaro is an exceptional seafront estate that blends history with luxury, offering an unparalleled lifestyle in one of the most sought after locations on Corfu.\n\nNestled on the beautiful northeastern coast of Corfu, just a five minute drive from the vibrant heart of Kassiopi, Kaniaro is truly one of a kind seafront estates offering the rare combination of historical charm and modern luxury. Originally an 18th-century olive press, this special property has been thoughtfully restored to preserve its original features while incorporating all the comforts of contemporary living. Set directly on the sea with private access to a sandy beach and a 10 meter jetty, Kaniaro presents a truly private and tranquil retreat.\n\nThe estate is approached through large electric gates, leading down a long, winding drive that meanders through ancient olive groves. The main building, located right next to the crystal clear waters of the Ionian Sea, offers sweeping views of the coastline. The grounds, spanning nearly 9,000 square meters, are beautifully landscaped with an array of Mediterranean flora, including circa sixty olive trees, pomegranates, lemons, oranges, kumquats, figs, almonds, and avocados, creating a lush and peaceful oasis.\n\nTo the north of the property lies a tranquil monastery and a stunning, secluded sandy beach, while to the south, within a short walk, another long sandy beach with restaurants offering a perfect mix of seclusion and convenience. The 20 meter infinity swimming pool, positioned on an elevated terrace, is nestled within the lush gardens and offers breathtaking views of the sea. The swimming pool area features ample sunbathing space, a fully equipped bar, an outdoor WC and shower facilities. For ultimate relaxation, there is also a private massage area and a fully equipped outdoor gym, both overlooking the sea.\n\nIn front of the main building, a vast terrace extends over the water, providing extensive outdoor sitting and dining areas, complete with a bar, pizza oven, and pergolas draped in mature wisteria. Just a few steps from the water, a private sunbathing area and floating 10 meter jetty offer direct access to the turquoise, sandy waters, where several boats can moor and one can swim in arguably some of the very best water in Greece.\n\nThe main villa is spread across two levels. On the ground floor, a spacious living room with a grand fireplace opens to the library and indoor dining area and a fully equipped kitchen with a large walk in cold room and separate guest WC. This level also features an independent bedroom with an ensuite bathroom and direct access to the lovely terrace. The first floor is dedicated to the master suite, which boasts a dressing room, a large ensuite bathroom with both a bathtub and a shower, and the bedroom has panoramic sea views. Additionally, there are three more bedrooms, each with its own shower rooms, two of which are ensuite, offering comfort and privacy for family and guests.\n\nAt the rear of the main villa, an independent guest house is positioned on a higher level, ensuring complete privacy. The building includes two double bedrooms on a mezzanine level, each with a sitting room, ensuite shower room, and private terraces. There is an en-suite studio room at the rear and on the ground level, there is an additional guest bedroom with an ensuite bathroom, plus there is a large laundry room with a WC.\n\nFor those looking to expand, the estate offers the possibility to build on the land. Pre-Approved Planning Permission for a 5 Bedroom ensuite bathrooms property of 186 m2 123 m2 basement on the land with direct sea access. Planning can be changed and simplified to add more guest suits and staff quarters to the main property.\n\nWhether you're looking for a family home or an exclusive holiday retreat, this unique property provides the perfect combination of privacy, elegance, and proximity to Corfu's natural beauty and vibrant local culture.",
    specifications: [
      { label: "Living Area", value: "5,878 sqft" },
      { label: "Lot Size", value: "2.22 ac" },
      { label: "Bedrooms", value: "9" },
      { label: "Bathrooms", value: "9" },
      { label: "Property Type", value: "Estate" },
      { label: "Year Built", value: "18th century" },
      { label: "Renovation", value: "Fully Restored" }
    ],
    features: [
      "Beachfront",
      "Water View",
      "Sea View",
      "Waterfront",
      "Seafront",
      "Privacy",
      "Panoramic / Scenic View",
      "Mansion",
      "Renovated",
      "Stone Countertops",
      "Library",
      "Air Conditioning",
      "Office",
      "Fitness Center / Gym",
      "High Ceiling",
      "Washer Dryer",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Fireplace",
      "Gas Stovetop",
      "Terrace",
      "Pergola",
      "Outdoor Living Space",
      "Parking",
      "Garden",
      "Balcony",
      "Private Beach",
      "Fire Pit",
      "Gate",
      "Pool",
      "Outdoor Kitchen",
      "Playground"
    ],
    visible: true
  },
  {
    id: 'dubai-creek-sky-mansion',
    title: "Dubai Creek Harbour View | 6 Br Sky Mansion Half Floor",
    location: "Business Bay - Dubai - United Arab Emirates, Dubai, Dubai, United Arab Emirates",
    specs: ["6 Bedrooms", "9 Bathrooms", "74,269 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2915-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2916-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2917-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2918-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2919-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2920-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2921-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2922-1.jpg"
    ],
    description: "Experience Ultra-Luxury Living in Dubai\n\nThis stunning Fleurs de Jardin Sky Mansion, named after the iconic Fleur de Jardin watch by Jacob & Co, offers a rare opportunity to own one of the most luxurious residences in the heart of Dubai.\nDirect from Developer | No Brokers | No Commission | Exclusive Inventory\n\nProperty Details:\n\n• Completion Date: June 2026\n• Type: Fleurs de Jardin Sky Mansion\n• Layout: 6 Bedrooms, Half Floor Residence\n• Bathrooms: 9\n• Master Suite: Walk-in Closet\n• Additional Spaces: Maid's Room, Laundry Area, Storage Room\n• Balconies: Expansive, offering breathtaking views\n• Living Area: Well-appointed and spacious\n• Kitchen: Modern and fully equipped\n• Amenities: Pool Lounge, Infinity Pool\n• Views: Panoramic Dubai Skyline, Dubai Creek Harbour, Dubai Design District, and Tower Garden\n\nKey Features:\n\n• State-of-the-art Gymnasium\n• Infinity Pool with spectacular views\n• Lobby Lounge for socializing and relaxation\n• Parking: Ample space for multiple vehicles\n• Security: 24/7 on-site security and concierge services\n\nThis is an unparalleled opportunity to own a Sky Mansion that redefines luxury. Every element of the Fleurs de Jardin Sky Mansion is crafted for those who desire the pinnacle of sophistication and elegance.",
    specifications: [
      { label: "Living Area", value: "74,269 sqft" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "9" },
      { label: "Property Type", value: "Sky Mansion" },
      { label: "Year Built", value: "2026" },
      { label: "Layout", value: "Half Floor" }
    ],
    features: [
      "City View",
      "Water View",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "Investment Property",
      "New Built",
      "Stone Countertops",
      "Elevator",
      "Air Conditioning",
      "Fitness Center / Gym",
      "Washer Dryer",
      "Bar",
      "Walk In Closet",
      "Jacuzzi",
      "Sauna",
      "Gas Stovetop",
      "Terrace",
      "Garage",
      "Basketball Court",
      "Parking",
      "Tennis Court",
      "Garden",
      "Balcony",
      "Pool",
      "Playground"
    ],
    visible: true
  },
  {
    id: 'alhambra-palace',
    title: "Alhambra Palace Luxury Living In Nueva Andalucia's Golf Valley",
    location: "Nueva Andalucía, 29660 Marbella, Málaga, Spain, Marbella, Andalusia, Spain",
    specs: ["12 Bedrooms", "11 Bathrooms", "15,791 sqft", "1.08 ac lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2903-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2904-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2905-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2906-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2907-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2908-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2909-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2910-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2911-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2912-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2913-1.jpg"
    ],
    description: "Luxurious Palatial Residence with Captivating Interiors in Nueva Andalucia\n\nDiscover the exquisite Alhambra Palace, an architectural marvel seamlessly fusing traditional Andalusian charm with Moorish influences. This palatial abode offers an enchanting and evocative living experience, set on an expansive plot exceeding 4000m2. More than just a residence, it's a sensory journey that embodies the essence of its surroundings.\n\nStep into the impeccably manicured gardens, featuring a lagoon-inspired private pool and a delightful outdoor pergola, inviting residents to indulge in serene luxury and leisure. Versatile terraces cater to intimate alfresco dining or tranquil relaxation, each corner meticulously landscaped for privacy and beauty.\n\nThe kitchen, a haven for culinary aficionados, exudes grandeur in design while offering ample storage, harmonizing functionality with aesthetics.\n\nInside, the villa showcases sophistication with carefully curated furnishings and fixtures, suffusing the living spaces with refined elegance. Abundant windows and glass sliding doors flood the interiors with natural light, seamlessly blending indoor and outdoor realms. The open-plan living and dining area, with its lofty ceilings, enhances the sense of grandeur and spaciousness.\n\nAlhambra Palace's unique architectural layout strikes a perfect balance between privacy and connectivity. En-suite guest bedrooms offer comfort and style, with direct access to the captivating central patio. The master bedroom, located on the ground level, is a luxurious sanctuary boasting impeccable design, a lavish private bathroom, and a spacious walk-in closet.\n\nDescending to the lower level, residents discover a plethora of amenities. A fully equipped outdoor gym beckons health enthusiasts, while a custom traditional bodega, entertainment room, and cinema room cater to leisure and social gatherings.\n\nIdeally situated in Nueva Andalucia's Golf Valley, Alhambra Palace offers unparalleled convenience. Quick access to amenities, world-class golf courses, Puerto Banus, and Marbella Golden Mile make it a residence of distinction, epitomizing an elevated lifestyle.\n\nQuality Specifications:\n\nFlooring:\n\nInternal: Wooden and marble.\nExternal: Marble floors in exterior terraces and patio.\nCarpentry:\n\nBlack aluminum windows with single glazing.\nKitchen & Laundry:\n\nLacanche cooker.\nGaggenau and Miele appliances.\nAir-Conditioning, Heating, Ventilation:\n\nHot/cold air conditioning throughout the house. No UFH.\nWater heating system with two 800L tanks.\nElectricity, Lighting, Sound, Smart Systems:\n\nNo domotic.\nWiFi.\nTVs: 85-inch Samsung television in the cinema, two Samsung televisions in bedrooms 3 and 4, and a television in the kitchen.\nAutomatic blinds.\nSecurity System:\n\nOperational alarm system.\nOther:\n\nSafety deposit boxes in some rooms.\nOutdoor jacuzzi.\nExterior pool.\nWater features: fountain and pond.\nAutomated irrigation system.",
    specifications: [
      { label: "Living Area", value: "15,791 sqft" },
      { label: "Lot Size", value: "1.08 ac" },
      { label: "Bedrooms", value: "12" },
      { label: "Bathrooms", value: "11" },
      { label: "Property Type", value: "Villa" }
    ],
    features: [
      "Ocean View",
      "City View",
      "Beachfront",
      "High Altitude",
      "Water View",
      "Golf View",
      "Coastal",
      "Sea View",
      "Lake View",
      "Gated Community",
      "Hilltop",
      "River View",
      "Mountain View",
      "Privacy",
      "Panoramic / Scenic View",
      "Duplex",
      "Mansion",
      "Modern",
      "Renovated",
      "Investment Property",
      "Indoor Pool",
      "Stone Countertops",
      "Elevator",
      "Library",
      "Steam Room",
      "Air Conditioning",
      "Office",
      "Fitness Center / Gym",
      "High Ceiling",
      "Washer Dryer",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Jacuzzi",
      "Cinema",
      "Open Kitchen",
      "Wine Cellar",
      "Fireplace",
      "Game Room",
      "Basement",
      "Sauna",
      "Gas Stovetop",
      "Terrace",
      "Garage",
      "Pergola",
      "Basketball Court",
      "Outdoor Living Space",
      "Parking",
      "Tennis Court",
      "Garden",
      "Balcony",
      "Private Beach",
      "Fire Pit",
      "Gate",
      "Pool",
      "Outdoor Kitchen",
      "Playground"
    ],
    visible: true
  },
  {
    id: 'whistler-ski-residence',
    title: "Masterfully Crafted Ski In/Ski Out Residence",
    location: "2932 Ancient Cedars Lane, Whistler, BC, V8E0L6, CANADA, Whistler, British Columbia, Canada",
    specs: ["7 Bedrooms", "9 Bathrooms", "6,326 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2884-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2885-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2886-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2887-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2888-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2890-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2891-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2892-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2893-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2894-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2895-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2896-1.jpg"
    ],
    description: "Perched on Whistler Mountain in the exclusive Kadenwood community, this masterfully crafted ski-in/ski-out residence seamlessly integrates nature with refined luxury. Thoughtfully curated by Brent Murdoch, Gavan Construction, & Project 22 Design, this residence features expansive windows framed by granite and old-growth forest, offering breathtaking views of Whistler Peak and the Tantalus Range. Outdoor living is redefined with heated patios, pool, and hot tub—perfect for unwinding after a day on the slopes. Inside, an intuitive layout caters to relaxation and entertaining, with multiple gathering spaces, a media room, and a wine cellar plus tasting room. The chef's kitchen, outfitted with top-tier Gaggenau appliances, custom Shinnoki Oak millwork, and Caesarstone quartz countertops, is a true culinary haven. An elevator ensures effortless access to all levels, while an oversized garage and ski/boot room provide ample storage. Complete with private neighbourhood gondola and convenient access to Whistler and Creekside villages, this is mountain living at its finest. Nightly rentals permitted.",
    specifications: [
      { label: "Living Area", value: "6,326 sqft" },
      { label: "Bedrooms", value: "7" },
      { label: "Bathrooms", value: "9" },
      { label: "Property Type", value: "House" }
    ],
    features: [
      "Water View",
      "Ski-In / Ski-Out",
      "Mountain View",
      "Stone Countertops",
      "Elevator",
      "High Ceiling",
      "Kitchen island",
      "Bar",
      "Walk In Closet",
      "Jacuzzi",
      "Cinema",
      "Wine Cellar",
      "Fireplace",
      "Gas Stovetop",
      "Terrace",
      "Garage",
      "Outdoor Living Space",
      "Balcony",
      "Fire Pit",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'palm-jebel-ali-mansion',
    title: "Ultra Luxury 5 Bedrooms Beachfront Mansion In Palm Jebel Ali Villas",
    location: "XXWG+VX - Mina Jebel Ali - Dubai - United Arab Emirates, Dubai, Dubai, United Arab Emirates",
    specs: ["5 Bedrooms", "5 Bathrooms", "7,569 sqft", "7,798 sqft lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2875-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2876-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2877-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2878-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2879-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2880-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2881-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2882-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2883-1.jpg"
    ],
    description: "Palm Jebel Ali's prime location is a major draw. It's close to Jebel Ali Port, a key trade hub. It's just 30 minutes from the newly opened Al Maktoum International Airport, set to be Dubai's largest and Emirates Airlines' headquarters. With the upcoming Etihad rail line, this area will offer seamless air, sea, and rail connectivity, making it a vital economic trade zone. Quick access to the Sheikh Zayed Road ensures you're near top-notch amenities like a championship golf course, marina, theme park, and luxury shopping mall.",
    specifications: [
      { label: "Living Area", value: "7,569 sqft" },
      { label: "Lot Size", value: "7,798 sqft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "5" },
      { label: "Property Type", value: "Mansion" }
    ],
    features: [
      "Beachfront",
      "Water View",
      "Gated Community",
      "Panoramic / Scenic View",
      "Mansion",
      "New Built",
      "Indoor Pool",
      "Elevator",
      "Air Conditioning",
      "High Ceiling",
      "Washer Dryer",
      "Kitchen island",
      "Laundry Room",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Outdoor Living Space",
      "Parking",
      "Garden",
      "Balcony",
      "Private Beach",
      "Gate",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'gandarinha-cascais-villa',
    title: "Gandarinha, Cascais – Ultra Luxury Oceanfront Villa With 6 Suites",
    location: "Gandarinha, Cascais, Portugal",
    specs: ["6 Bedrooms", "7 Bathrooms", "8,611 sqft", "0.74 ac lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2865-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2866-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2867-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2868-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2869-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2870-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2871-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2872-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2873-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2874-1.jpg"
    ],
    description: "Discover this extraordinary oceanfront villa in Gandarinha, Cascais, where luxury meets coastal living. This magnificent property offers breathtaking views of the Atlantic Ocean and provides an unparalleled living experience.\n\nSet on a generous plot of 3,000 m², this villa features 800 m² of meticulously designed living space. The property includes 6 elegant suites, spacious living areas, and state-of-the-art amenities. The architectural design maximizes the stunning ocean views while ensuring privacy and comfort.\n\nThe villa's exterior spaces are equally impressive, featuring a large swimming pool, beautifully landscaped gardens, and multiple terraces perfect for outdoor entertaining. The property's location in Gandarinha, one of Cascais's most prestigious areas, offers easy access to beaches, golf courses, and the charming Cascais town center.\n\nKey Features:\n- 6 luxurious suites\n- Panoramic ocean views\n- Large swimming pool\n- Landscaped gardens\n- Multiple terraces\n- High-end finishes throughout\n- Private parking\n- Security system\n- Smart home technology",
    specifications: [
      { label: "Living Area", value: "8,611 sqft" },
      { label: "Lot Size", value: "0.74 ac" },
      { label: "Bedrooms", value: "6" },
      { label: "Bathrooms", value: "7" },
      { label: "Property Type", value: "Villa" },
      { label: "View", value: "Ocean" }
    ],
    features: [
      "Ocean View",
      "Beachfront",
      "Waterfront",
      "Coastal",
      "Sea View",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Garden",
      "Balcony",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'woodley-park-residence',
    title: "2833 27th St Nw",
    location: "Washington, District of Columbia, United States",
    specs: ["7 Bedrooms", "7 Bathrooms", "6,900 sqft", "0.23 ac lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1868.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1869.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1870.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1871.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1877.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1879.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1887.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1888.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1891.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1895.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_1894.jpg"
    ],
    description: "Welcome to this extraordinary residence in Washington DC's prestigious Woodley Park neighborhood. This meticulously renovated home combines classic architecture with modern luxury, offering approximately 6,900 square feet of sophisticated living space.\n\nThe main level features a grand foyer, formal living and dining rooms, and a gourmet kitchen that opens to a family room with French doors leading to a private terrace. The chef's kitchen is equipped with premium appliances, custom cabinetry, and a large center island.\n\nThe upper levels house seven bedrooms including a luxurious primary suite with a sitting area, custom walk-in closets, and a spa-like bathroom. Additional bedrooms feature en-suite bathrooms and ample closet space.\n\nThe lower level includes a recreation room, wine cellar, and additional storage space. The property also features a two-car garage, professionally landscaped grounds, and multiple outdoor living spaces.\n\nKey Features:\n- Completely renovated\n- Gourmet kitchen\n- Wine cellar\n- Multiple fireplaces\n- Two-car garage\n- Private terrace\n- Smart home technology\n- Security system",
    specifications: [
      { label: "Living Area", value: "6,900 sqft" },
      { label: "Lot Size", value: "0.23 ac" },
      { label: "Bedrooms", value: "7" },
      { label: "Bathrooms", value: "7" },
      { label: "Property Type", value: "Single Family Home" },
      { label: "Year Built", value: "1925" },
      { label: "Renovation", value: "2023" }
    ],
    features: [
      "Privacy",
      "Renovated",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Wine Cellar",
      "Fireplace",
      "Terrace",
      "Garage",
      "Garden",
      "Balcony"
    ],
    visible: true
  },
  {
    id: 'nad-al-sheba-villa',
    title: "Luxury 5 Bedroom Villa in Nad Al Sheba",
    location: "Nad Al Sheba - Dubai - United Arab Emirates",
    specs: ["5 Bedrooms", "6 Bathrooms", "6,000 sqft", "8,000 sqft lot"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2080.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2081.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2084.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2085.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2088.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2090.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2095.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2098.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2102.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2104.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2105.jpg"
    ],
    description: "Experience luxury living in this contemporary villa located in the prestigious Nad Al Sheba community. This stunning property combines modern architecture with premium finishes and amenities, creating an ideal family home in Dubai.\n\nThe villa features a spacious open-plan layout with high ceilings and floor-to-ceiling windows that flood the interior with natural light. The ground floor includes a formal living room, family room, dining area, and a state-of-the-art kitchen equipped with premium appliances and custom cabinetry.\n\nThe five bedrooms are thoughtfully designed with en-suite bathrooms and built-in wardrobes. The master suite offers a private balcony, walk-in closet, and a luxurious bathroom with dual vanities and a freestanding tub.\n\nOutdoor amenities include a private swimming pool, landscaped garden, and covered parking for multiple vehicles. The property also features smart home technology, security systems, and maid's quarters.\n\nKey Features:\n- Contemporary design\n- Smart home technology\n- Private swimming pool\n- Covered parking\n- Maid's quarters\n- Security system\n- Premium finishes throughout",
    specifications: [
      { label: "Living Area", value: "6,000 sqft" },
      { label: "Lot Size", value: "8,000 sqft" },
      { label: "Bedrooms", value: "5" },
      { label: "Bathrooms", value: "6" },
      { label: "Property Type", value: "Villa" },
      { label: "Year Built", value: "2023" }
    ],
    features: [
      "Privacy",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Bar",
      "Laundry Room",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Garden",
      "Balcony",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'marbella-duplex-penthouse',
    title: "Stunning Duplex Penthouse With Breathtaking Views",
    location: "Marbella, Málaga, Spain",
    specs: ["4 Bedrooms", "4 Bathrooms", "3,875 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2007.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2008.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2010.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2011.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2013.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2014.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2016.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2019.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2023.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2026.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2025.jpg"
    ],
    description: "This exceptional duplex penthouse in Marbella offers luxurious living with panoramic views of the Mediterranean Sea and mountains. Located in a prestigious gated community, this property combines contemporary design with premium finishes and amenities.\n\nThe lower level features an open-plan living area with floor-to-ceiling windows, a modern kitchen with high-end appliances, and access to a spacious terrace perfect for outdoor dining and entertaining. The upper level houses the master suite with a private terrace, walk-in closet, and luxury bathroom, plus additional en-suite bedrooms.\n\nThe property includes multiple terraces offering stunning views, a private pool, and covered parking. Residents have access to community amenities including gardens, pools, and 24-hour security.\n\nKey Features:\n- Panoramic sea and mountain views\n- Private pool\n- Multiple terraces\n- High-end finishes\n- Smart home technology\n- 24-hour security\n- Covered parking\n- Community amenities",
    specifications: [
      { label: "Living Area", value: "3,875 sqft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "4" },
      { label: "Property Type", value: "Penthouse" },
      { label: "Year Built", value: "2023" }
    ],
    features: [
      "Ocean View",
      "Mountain View",
      "Sea View",
      "Gated Community",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Air Conditioning",
      "High Ceiling",
      "Kitchen island",
      "Walk In Closet",
      "Open Kitchen",
      "Terrace",
      "Garage",
      "Balcony",
      "Pool"
    ],
    visible: true
  },
  {
    id: 'business-bay-57j6',
    title: "Business Bay 57J6 Dubai",
    location: "Business Bay - Dubai - United Arab Emirates",
    specs: ["4 Bedrooms", "5 Bathrooms", "4,500 sqft"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_2052.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2054.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2056.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2057.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2059.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2062.jpg","https://image931.wordpress.com/wp-content/uploads/2025/04/img_2063.jpg"
    ],
    description: "Experience luxury living in this stunning apartment located in Dubai's prestigious Business Bay district. This contemporary residence offers breathtaking views of the Dubai skyline and Burj Khalifa, combining modern design with premium finishes and amenities.\n\nThe apartment features an open-plan living space with floor-to-ceiling windows that flood the interior with natural light and showcase the spectacular city views. The modern kitchen is equipped with high-end appliances and custom cabinetry, perfect for both everyday living and entertaining.\n\nAll four bedrooms include en-suite bathrooms and built-in wardrobes, with the master suite offering a walk-in closet and a luxury bathroom. The property also features a maid's room with its own bathroom.\n\nResidents have access to world-class amenities including a swimming pool, fitness center, children's play area, and 24-hour security. The location offers easy access to Downtown Dubai, Dubai Mall, and major transportation links.\n\nKey Features:\n- Burj Khalifa and city views\n- Premium finishes\n- Smart home technology\n- Building amenities\n- 24-hour security\n- Parking space\n- Central location",
    specifications: [
      { label: "Living Area", value: "4,500 sqft" },
      { label: "Bedrooms", value: "4" },
      { label: "Bathrooms", value: "5" },
      { label: "Property Type", value: "Apartment" },
      { label: "Year Built", value: "2023" }
    ],
    features: [
      "City View",
      "Privacy",
      "Panoramic / Scenic View",
      "Modern",
      "New Built",
      "Stone Countertops",
      "Elevator",
      "Air Conditioning",
      "Fitness Center / Gym",
      "Kitchen island",
      "Walk In Closet",
      "Open Kitchen",
      "Balcony",
      "Pool"
    ],
    visible: true
  }
];