import { YachtListing } from './yachtTypes';

export const yachtListings: YachtListing[] = [
  {
    id: 'cranchi-sessantadue-62',
    title: "CRANCHI Sessantadue 62",
    location: "France",
    year: "2025",
    specs: ["66 ft Length", "Flybridge", "Powerboat"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2934-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2935-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2936-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2937-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2938-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2939-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2940-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2941-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2942-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/05/img_2943-1.jpg"
    ],
    description: "TO ORDER : Starting price without options! Impossible to look away from right from the very first glance: the design element which first affirms the character of the Sessantadue 62 is its vertical bow. A line which connects the sea and sky, and which accentuates the naval allure of the yacht. The waterline is lengthened, with the vessel benefiting in terms of audacity and muscularity, but without suffering in terms of harmony of forms, which is a distinctive element of Cranchi Yachts' new flybridge models. The information provided is believed to be accurate. However, they are not guaranteed and cannot form the basis of a contract.",
    specifications: [
      { label: "Year", value: "2025" },
      { label: "Location", value: "France" },
      { label: "Condition", value: "New" },
      { label: "Category", value: "Powerboat" },
      { label: "Type", value: "Flybridge" },
      { label: "Length", value: "20 m (66 ft)" },
      { label: "Beam", value: "5 m (16 ft)" },
      { label: "Draft", value: "0 m (0 ft)" },
      { label: "Displacement", value: "0 kg (0 lbs)" },
      { label: "VAT", value: "VAT Included" },
      { label: "Reference", value: "3698" }
    ],
    features: [
      "Vertical Bow Design",
      "Flybridge",
      "Powerboat Category",
      "New Condition",
      "VAT Included",
      "Latest Model",
      "Cranchi Yachts Build",
      "Modern Design",
      "Spacious Layout"
    ],
    visible: true
  },
  {
    id: 'spitfire',
    title: "SPITFIRE",
    location: "Antalya, Turkey",
    year: "2027",
    specs: ["165.8 ft Length", "5 Guest Cabins", "22 Knots Max Speed"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img25-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img22-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img32-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img36-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img52-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img56-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img75-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img83-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img105-1.jpg?w=1024",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img109-1.jpg?w=1022",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img124-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img132-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img264-1.jpg?w=1024"
    ],
    description: "Project SPITFIRE is a collaboration between some of the most well-known names in their respected fields of expertise. Iconic design firm Bannenberg & Rowell and Lateral Naval Architects have joined forces with ARES Shipyard based in Antalya, Turkey to bring to you SPITFIRE, a diesel electric hybrid sport yacht with expansive exterior deck spaces, beach club & wellness area, floor to ceiling glass walls, timeless lines and fantastic capabilities. She is sub 500GRT, has an impressive top speed of 22 knots which is appropriate with her low profile sport lines yet at economical speeds still has a 3,500nm range. SPITFIRE sleeps 10 guests in 5 cabins and has expansive crew accommodations for up to 9 in 5 cabins. Built to RINA Commercial, Green Plus classification, LY3.\n\nThe design of SPITFIRE calls on the heritage of the legendary Spitfire fighter aircraft with the goal of creating its own legacy. Lateral Naval Architects have developed the hull form to be fast, efficient and keeping with the future implemented a diesel electric hybrid package which optimizes running costs with multiple modes to be applied to a variety of conditions when cruising. Bannenberg & Rowell has been able to create a light and airy interior décor that incorporates glass, light woods & textures that give a zen like feeling which I feel translates to modern day yachting. SPITFIRE will redefine the sport yacht segment of the market and establish ARES Shipyard as one of the premier builders in this segment of the market.\n\nConstruction on SPITFIRE will begin in February 2025 and is a 24 month construction period with delivery scheduled for Spring 2027. SPITFIRE has been fully developed with all technical specifications for Lateral Naval Architects finalized as well as the interior & exterior design elements by Bannenberg & Rowell.\n\nARES Shipyard located in the Antalya Free Trade Zone is one of the most impressive facilities I| have seen of any shipyard not just in Turkey. ARES is extremely well respected as the country's largest exporter of military & commercial vessels. This award winning, family run operation has now entered the yachting segment of the market with every intention of duplicating their success with SPITFIRE. Financially strong with unlimited resources, expect to hear more from ARES in the coming year.",
    specifications: [
      { label: "Length", value: "50.55 m/165.8 ft" },
      { label: "Beam", value: "8.58 m/6.2 ft" },
      { label: "Draft", value: "2.01 m/6.6 ft" },
      { label: "Gross Tonnage", value: "499" },
      { label: "Year", value: "2027" },
      { label: "Builder", value: "Ares" },
      { label: "Cruising Speed", value: "10 knots" },
      { label: "Max Speed", value: "22 knots" },
      { label: "Range", value: "3,500 nm" },
      { label: "Classification", value: "RINA C+ Hull Match \"Ych\", Unrestricted, DMS, Green Plus, Hybrid Propulsion" },
      { label: "Hull Construction", value: "Advanced composite" },
      { label: "Superstructure", value: "Advanced composite" },
      { label: "Guests", value: "10" },
      { label: "Staterooms", value: "5" },
      { label: "Flag", value: "Cayman Islands" }
    ],
    features: [
      "Diesel Electric Hybrid Propulsion",
      "Beach Club & Wellness Area",
      "Floor to Ceiling Glass Walls",
      "Expansive Deck Spaces",
      "5 Guest Cabins",
      "Crew Accommodation for 9",
      "Green Plus Classification",
      "Sport Yacht Design",
      "Bannenberg & Rowell Interior",
      "Lateral Naval Architects Hull",
      "Advanced Composite Construction",
      "Long Range Capability",
      "Hybrid Operating Modes",
      "Zen-like Interior Design",
      "Light Woods & Textures"
    ],
    visible: true
  },
  {
    id: 'magnolia-2026',
    title: "MAGNOLIA2026",
    location: "Donaueschingen, Turkey",
    year: "2026",
    specs: ["134 ft Length", "5 Guest Cabins", "Motor Yacht"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img29-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img12-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img28-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img30-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img33-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img36-2-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img37-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img38-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img39-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img41-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img47-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img48-1.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img55-1.jpg"
    ],
    description: "The Magnolia 41 meter is a large volume (485 GT) super yacht designed for unparalleled guest experiences and comfort.\n\nShe is the first of a series and features a steel hull and aluminum superstructure. This ocean-going vessel embodies the highest standards of design, construction, fuel-efficiency, safety and comfort.\n\nThe striking exterior design is by the internationally renowned Gregory C Marshall Naval Architects, ensuring a yacht that is not only beautiful but also performs exceptionally. We are committed to environmentally conscious yachting and are incorporating technologically innovative features to minimize our impact on the oceans. The interior is made in neutral color palette and has a modern and cool feel. The yacht is built to ocean-going specifications, ready to explore the world's most captivating destinations.\n\nMagnolia Yachts is dedicated to building tailor-made, unique yachts, where meticulous attention to detail is paramount.\n\nEach project is carefully crafted and built with unwavering precision every step of the way. Established in 2019 by the fourth generation of the Yardimci family, whose 50 year legacy in shipbuilding and ship-owning spans decades, Magnolia Yachts brings a wealth of experience to the luxury yacht market. After years of building and managing commercial ships, the family has channeled their expertise and passion into creating exceptional, custom-made super yachts for discerning clients",
    specifications: [
      { label: "Make", value: "Custom" },
      { label: "Model", value: "Magnolia Yachts" },
      { label: "Year", value: "2026" },
      { label: "Length", value: "134 ft" },
      { label: "Condition", value: "New" },
      { label: "Class", value: "Motor Yacht" },
      { label: "Hull Material", value: "Steel" },
      { label: "Beam", value: "28 ft 10 in" },
      { label: "Location", value: "Turkey" },
      { label: "Name", value: "MAGNOLIA" },
      { label: "Guest Cabins", value: "5" },
      { label: "Guest Heads", value: "8" },
      { label: "Fuel Type", value: "Diesel" },
      { label: "Max Speed", value: "15 kn" },
      { label: "Max Draft", value: "8 ft 9 in" }
    ],
    features: [
      "Steel Hull Construction",
      "Aluminum Superstructure",
      "Gregory C Marshall Design",
      "Eco-Friendly Features",
      "Modern Interior",
      "Neutral Color Palette",
      "Ocean-Going Specifications",
      "5 Guest Cabins",
      "8 Guest Heads",
      "485 GT Volume",
      "Custom Build",
      "Fuel Efficient Design"
    ],
    visible: true
  },
  {
    id: 'formula-430-ssc',
    title: "Formula 430 SSC",
    location: "United States",
    year: "2022",
    specs: ["46 ft Length", "132 Engine Hours", "Quad Mercury 450R's"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1820.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1813.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1805.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1743.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1804.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1781.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1773.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1772.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1771.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1766.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1764.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1756.jpg"
    ],
    description: "Don't wait on this like NEW, lightly used 2022 Formula 430 SSC.\n\nSkip the build wait!\n\nWith less than 70 hours put on her, this 2022 model can be had with NO WAIT and last year's pricing! Conveniently located in Fort Lauderdale, FL. The Formula 430 SSC offers comfort for the entire family. Offering an extremely stable platform, equipped with Quad Mercury 450R's and top speeds of 71MPH. Enjoy the expansive seating arrangements, Sat TV, cold storage, convertible seating/lounge space, and premier sound system. The Seakeeper ensures all guests are comfortable while enjoying the features of this crossover bowrider. Make yourself comfortable with an A/C filled cabin, equipped with full head and stand-up shower, fully equipped dinette, and convertible dining area. Lounge on the aft deck under the electric shade cover, or enjoy the forward seating while underway.\n\nThe Formula 430 Super Sport Crossover is an innovative concept destined to revolutionize offshore boating. This model truly offers the best of both worlds. It blends the command of Formula Boats' smooth performance heritage with the cabin and open bow elements that come from our unparalleled Crossover Bowrider.",
    specifications: [
      { label: "Year", value: "2022" },
      { label: "Location", value: "United States" },
      { label: "Condition", value: "Used" },
      { label: "Category", value: "Sailboat" },
      { label: "Type", value: "Cruiser" },
      { label: "Length", value: "46 ft (14 m)" },
      { label: "Beam", value: "12 ft (4 m)" },
      { label: "Draft", value: "3 ft (1 m)" },
      { label: "Engine Power", value: "450 hp" },
      { label: "Engine Hours", value: "132" },
      { label: "Reference", value: "963703" }
    ],
    features: [
      "Quad Mercury 450R's",
      "Formula Guard Warranty until 2027",
      "11kw Kohler Diesel Generator",
      "Progressive hydraulic bow thruster",
      "Joystick Control",
      "Seakeeper Stabilization",
      "Electric sunshade",
      "Electric Blue Metallic w/steel metallic accent",
      "Stand up head with shower",
      "Full bed in aft stateroom",
      "Expansive seating areas",
      "Raymarine electronics",
      "Autopilot",
      "Mercury vessel view",
      "Rock Fosgate stereo",
      "Upgraded countertops"
    ],
    visible: true
  },
  {
    id: 'hatteras-64-motor-yacht',
    title: "Hatteras 64 Motor Yacht",
    location: "United States",
    year: "2006",
    specs: ["64 ft Length", "2,300 Engine Hours", "Motor Yacht"],
    images: [
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1671.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1674.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1678.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1684.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1688.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1691.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1698.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1707.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1718.jpg",
      "https://image931.wordpress.com/wp-content/uploads/2025/04/img_1716.jpg"
    ],
    description: "VOLARE WILL BE LOCATED 5 MINUTES FROM THE FORT LAUDERDALE BOAT SHOW AT THE ROYAL PALM MARINA IN DANIA BEACH.\n\n\"Volare\" was recently purchased and in pristine condition. She has a 3 stateroom 3 head layout. She comes with Cat 3412's with aprox 2300hrs. Her exterior, upholstery, teak etc is in excellent condition. She was kept under cover from the previous owner. Turn key, a 9.",
    specifications: [
      { label: "Year", value: "2006" },
      { label: "Location", value: "United States" },
      { label: "Condition", value: "Used" },
      { label: "Category", value: "Sailboat" },
      { label: "Type", value: "Motor Yacht" },
      { label: "Length", value: "64 ft (20 m)" },
      { label: "Beam", value: "18 ft (5 m)" },
      { label: "Draft", value: "5 ft (2 m)" },
      { label: "Engine Power", value: "1400 hp" },
      { label: "Engine Hours", value: "2300" },
      { label: "Reference", value: "9545438" }
    ],
    features: [
      "Cat 3412s (w/2300hrs) 2000 hr service completed",
      "Twin 21kw Onan generators (Starboard brand new)",
      "Bow thruster",
      "Stern wing station",
      "Upgraded Garmin 8215 electronics package",
      "11ft Avon tender with 40hp Yamaha 4 stroke",
      "Recent bottom w/Prop speed job Feb 2023",
      "Complete engine and generator service Feb 2023",
      "Upgraded sound system interior/cockpit and Flybridge",
      "2 KVH satellite systems Dish Network/Direct TV",
      "New Pep Wave Wi Fi",
      "New AC pumps"
    ],
    visible: true
  }
];